//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YarraTrams.Havm2TramTracker.Models.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLEXPRESS;Initial Catalog=TramTracker;Integrated Security=" +
            "True")]
        public string TramTrackerConnectionString {
            get {
                return ((string)(this["TramTrackerConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>c</string>\r\n  <string>d1</string>\r\n  <string>d2</string>\r\n</ArrayOfString>" +
            "")]
        public global::System.Collections.Specialized.StringCollection VehicleGroupsWithLowFloor {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VehicleGroupsWithLowFloor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>a</string>
  <string>b</string>
  <string>c1</string>
  <string>c2</string>
  <string>car</string>
  <string>e</string>
  <string>e1</string>
  <string>l</string>
  <string>taxi</string>
  <string>w</string>
  <string>z</string>
  <string>z3</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VehicleGroupsWithoutLowFloor {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VehicleGroupsWithoutLowFloor"]));
            }
        }
    }
}
